export const roasters = [
    "Ruby Coffee Roasters",
    "Royal Mile Coffee",
    "Merit Coffee",
    "Manzanita Roasting",
    "Coava Coffee",
    "Camber Coffee",
    "Wrecking Ball Coffee",
    "Triple Coffee Co.",
    "Treeline Coffee Roasters",
    "George Howell Coffee",
    "Onyx Coffee Lab",
    "Verve Coffee Roasters",
    "Sweet Bloom Coffee",
    "Stumptown Coffee Roasters",
    "Slate Coffee Roasters",
    "Take Flight Coffee Roasters",
    "PT’s Coffee Roasting Co.",
    "Madcap Coffee",
    "Sey Coffee",
    "La Colombe Coffee",
    "Intelligentsia Coffee",
    "Heart Coffee Roasters",
    "Four Barrel Coffee",
    "Counter Culture",
    "Blue Bottle",
  ];
  
  export const coffee_types = ["Light", "Medium", "Medium/Dark", "Dark"];